# Generated by Django 3.0.8 on 2020-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_about_face',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('status', models.CharField(db_column='status', max_length=255)),
                ('path', models.CharField(db_column='path', max_length=255)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
    ]
