# Generated by Django 3.0.8 on 2020-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceidentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_about_face',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
