# Generated by Django 3.0.8 on 2020-07-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceidentification', '0002_auto_20200715_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_about_face',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
