# Generated by Django 3.0.8 on 2020-07-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceidentification', '0003_auto_20200715_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_status',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('status', models.CharField(db_column='status', max_length=255)),
                ('path_image', models.CharField(db_column='path_image', max_length=255)),
            ],
        ),
    ]
