# Generated by Django 3.0.8 on 2020-07-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceidentification', '0004_access_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_status',
            name='path_image',
        ),
        migrations.AddField(
            model_name='info_about_face',
            name='path_image',
            field=models.CharField(db_column='path_image', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
