# Generated by Django 3.0.8 on 2020-07-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceidentification', '0006_auto_20200721_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info_about_face',
            old_name='path',
            new_name='path_screen',
        ),
    ]
