# Generated by Django 3.0.8 on 2020-07-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceidentification', '0008_auto_20200721_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_status',
            name='path_image',
            field=models.CharField(db_column='path_image', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
