# Generated by Django 3.0.8 on 2020-07-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceidentification', '0009_access_status_path_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access_status',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='access_status',
            name='path_download',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
