# Generated by Django 3.0.8 on 2020-07-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceidentification', '0010_auto_20200722_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_status',
            name='path_image',
        ),
    ]
