# Generated by Django 3.0.8 on 2020-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceidentification', '0011_remove_access_status_path_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_status',
            name='path_download',
            field=models.ImageField(upload_to=''),
        ),
    ]
